### ISSUE TITLE
Create and return parsers for all methods in the services inside Clients::Azure

### ISSUE THREAD

**Issue by kaiomagalhaes** [codelittinc/roadrunner#239]

**Comment by viniciusaa** [comment]
Update azure client to return a parsed pull request.
https://github.com/codelittinc/roadrunner/pull/259

**Comment by viniciusaa** [comment]
Update azure client to return a parsed release list.
https://github.com/codelittinc/roadrunner/pull/260

**Comment by viniciusaa** [comment]
Azure release, create method now returns the correct data.
https://github.com/codelittinc/roadrunner/pull/262
