### ISSUE TITLE
Add all methods under Clients::Azure and Clients::Github to Clients::Azure::SourceControlClient

### ISSUE THREAD

**Issue by kaiomagalhaes** [codelittinc/roadrunner#240]
1. We need to assure that depending on the repository type it will call the github or the azure one
2. We need tests for each method
3. When the name of the method doesn't explain itself, i.e: `commits` we rename it in the interface to a better one like `list_pullrequest_commits`

**Comment by viniciusaa** [comment]
add more methods to source control client.
https://github.com/codelittinc/roadrunner/pull/235
