### ISSUE TITLE
Set the deploy_status of an application in the DeployNotificationFlow

### ISSUE THREAD

**Issue by kaiomagalhaes** [codelittinc/roadrunner#249]
In the DeployNotificationFlow we should update the repository's *latest* release deploy_status accordingly to what we receive in the flow.

**Comment by kaiomagalhaes** [comment]
depends on #248

**Comment by viniciusaa** [comment]
Updated latest release deploy_status when the a notification is deployed
https://github.com/codelittinc/roadrunner/pull/276
