### ISSUE TITLE
verify and replace any Github client call by the source_control_client

### ISSUE THREAD

**Issue by kaiomagalhaes** [codelittinc/roadrunner#269]

**Comment by viniciusaa** [comment]
Add source_control_client to BaseFlow and replace Github client for it on all flows
https://github.com/codelittinc/roadrunner/pull/270

**Comment by kaiomagalhaes** [comment]
@viniciusaa we need to update the hotfix_release_flow

**Comment by viniciusaa** [comment]
Update hotfix_release_flow to use source_control_client instead of github client.
https://github.com/codelittinc/roadrunner/pull/275
