### ISSUE TITLE
Store all json requests

### ISSUE THREAD

**Issue by kaiomagalhaes** [codelittinc/roadrunner#28]
Currently whenever we receive a new request we check if we have a flow for it or not. The problem is that when we find a new request that we need to build a flow for, we don't know how the payload is. The goal here is to create a new model called `Request` that will have the following format:

```
{
  json: <JSON PAYLOAD>,
  processed: true/false (depending on the fact that we did or not processed it
}
```

**Comment by Ascinocco** [comment]
@kaiomagalhaes should request extend the `BaseModel` class? It doesn't seem like it will use the methods `BaseModel` provides.

**Comment by Ascinocco** [comment]
@kaiomagalhaes I've opened a PR, but I'm not certain I've understood the problem holistically. https://github.com/codelittinc/roadrunner/pull/29
