### ISSUE TITLE
Update source control client methods to pass the repository object

### ISSUE THREAD

**Issue by kaiomagalhaes** [codelittinc/roadrunner#282]
The Github clients will use the `repository.full_name` and the Azure one will receive the `repository.name`

**Comment by viniciusaa** [comment]
Update source control client methods to receive repository object ins tead of name string
https://github.com/codelittinc/roadrunner/pull/283

**Comment by kaiomagalhaes** [comment]
@viniciusaa you need to update it here as well https://github.com/codelittinc/roadrunner/blob/master/app/services/parsers/github_webhook_parser.rb#L27

**Comment by viniciusaa** [comment]
Update GithubWebhookParser destroy_branch! method params to get the pull_request repository name instead of full_name
https://github.com/codelittinc/roadrunner/pull/288
